### ISSUE TITLE
no license

### ISSUE THREAD

**Issue by darantasiaa** [RodrigoRosmaninho/selfhosted-overleaf-backup#1]
Hello, 

Nice app and very useful but you applied no license on it. It would be nice if you did!

Thank you

Darant

**Comment by RodrigoRosmaninho** [comment]
@darantasiaa thanks for the reminder!
I have just added an MIT License.
Please let me know if you were hoping for something different.

**Comment by RodrigoRosmaninho** [comment]
@darantasiaa thanks for the reminder!
I have just added an MIT License.
Please let me know if you were hoping for something different.

**Comment by darantasiaa** [comment]
@RodrigoRosmaninho Thanks a lot :)
Have a nice day
